---
title: "p8105_hw6_qw2282"
author: "Qinyao Wu"
date: "11/17/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

```

```{r}


delete_city = c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL")

data_homicide = read.csv(file = "./data/homicide-data.csv") %>% 
  mutate(city_state = str_c(city,", ", state), 
         victim_age = as.numeric(victim_age),
         victim_race = fct_relevel(victim_race, "White")) %>% 
  select(-city, -state) %>% 
  
  #Use the function to define each case as arrested or unarrested. 
  mutate(resolved = as.numeric(disposition == "Closed by arrest")) %>% 
  filter( !(city_state %in% delete_city)) %>% 
  mutate(victim_race = forcats::fct_relevel(victim_race, ref = "White")) %>% 
  mutate(cat_race = factor(ifelse(victim_race == "White", "white", "Non-white"))) %>% 
  mutate(cat_race = relevel(cat_race, ref = "white")) 
 
baltimore_df = 
  data_homicide %>% 
   filter(city_state == "Baltimore, MD") %>% 
  select(resolved, victim_age, victim_race, victim_sex) 

fit_logistic = 
  baltimore_df %>% 
  glm(resolved ~ victim_age + victim_race + victim_sex, data = ., family = binomial()) 

result_df = 
  fit_logistic %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate), 
         ci_lower = exp(estimate - qnorm(0.975) * std.error),
         ci_upper =  exp(estimate + qnorm(0.975) * std.error)) %>% 
  filter(term == "victim_raceBlack")




 ################################
a = data_homicide %>%   
  mutate(resolved = as.numeric(disposition == "Closed by arrest"),
         victim_age = as.numeric(victim_age),
         victim_race = fct_relevel(victim_race, "White"))
levels(a$victim_race)
#################################
```


```{r}
OR_city_state = data_homicide %>% 
  select(city_state, resolved, victim_age, victim_race, victim_sex) %>% 
  group_by(city_state) %>% 
  nest() %>% 
  mutate(result = map(data, ~glm(resolved ~ victim_age + victim_race + victim_sex, data = ., family = binomial()))) %>%
select(-data) %>%
   
  mutate(result_tidy = map(result, broom::tidy)) %>%
  unnest(result_tidy) %>% 
  #filter(term == "victim_raceBlack") %>% 
  mutate(OR = exp(estimate), 
         ci_lower = exp(estimate - qnorm(0.975) * std.error),
         ci_upper =  exp(estimate + qnorm(0.975) * std.error)) %>%
  select(city_state, term, log_OR = estimate, OR, p.value, ci_lower, ci_upper) %>% 
  filter(term == "victim_raceBlack") %>% 
  mutate(city_state = forcats::fct_reorder(factor(city_state), OR)) 


ggplot(OR_city_state, aes( x = city_state, y = OR)) +
  geom_point(aes(size = 5, col = "blue")) +
  
  #Add the error bar. 
  geom_errorbar(aes(x = city_state, ymin = ci_lower, ymax = ci_upper)) +
  theme(text = element_text(size = 8), axis.text.x = element_text(angle = 60, hjust = 1)) + 
  
  #Add the title and the name for x and y axis. 
  labs(
    title = "OR estimation of Different City State of Black People",
    x = "City State",
    y = "Estimation of OR of unsolved Black homicides"
  )
```

###Problem 2

```{r}
data_birthweight = read.csv(file = "./data/birthweight.csv") %>% 
  janitor::clean_names() %>% 
  mutate(babysex = as.factor(babysex),
         malform = as.factor(malform),
         frace = as.factor(frace),
         mrace = as.factor(mrace))

####Build model

###Use stepwise function
mult.fit = lm(bwt ~ ., data = data_birthweight)
step(mult.fit, direction = 'backward')



design_model = lm(bwt ~ babysex + bhead + blength + delwt + fincome + 
    gaweeks + mheight + mrace + parity + ppwt + smoken + babysex * bhead, data = data_birthweight) %>% 
  summary()



```





```{r}
###Model with birth length and gaweeks
fit_lenth_gage = lm(bwt ~ blength + gaweeks, data = data_birthweight) %>% 
  summary()
  broom::tidy()

data_birthweight %>% 
  modelr::add_residuals(fit_lenth_gage) %>% 
  ggplot(aes(x = gaweeks, y = resid)) + geom_violin()


###Model with three way interaction
fit_three = lm(bwt ~ blength + babysex + bhead + blength * babysex * bhead, data = data_birthweight) %>% 
  summary()
  broom::tidy()

```

